### ISSUE TITLE
I want it on the i3 model

### ISSUE THREAD

**Issue by PremuimPython40** [balopez83/Surface-Pro-7-Hackintosh#2] opened 2024-03-29 14:56 UTC
What do i need to do?

**Comment by balopez83** [comment] 2024-03-29 16:19
First, you should attempt to boot using the i5 config and see if that works. Assuming it works without graphics glitches then you should be good to go. 

The i3 supposedly uses a different graphics chipset and so I do need its model identifier if the i5 config does not work. You can find this information in "Device Manager" in Windows.

**Comment by PremuimPython40** [comment] 2024-03-29 17:30
Hi, the i5 config is stuck at less then 1 min remaining.

Op vr 29 mrt 2024 om 17:19 schreef balopez83 ***@***.***>:

**Comment by balopez83** [comment] 2024-03-29 17:44
@PremuimPython40 Ok then it looks like the graphics is incompatible with the current configs.

Please boot into windows and provide the graphics model and if you can find it, the framebuffer identifier. You can find the graphics model in the device manager in windows

**Comment by balopez83** [comment] 2024-03-29 17:48
@PremuimPython40  Specifically I need to know exactly which UHD model your i3 has. I am unable to determine which one it is online

**Comment by balopez83** [comment] 2024-03-29 18:02
@PremuimPython40 After further research it appears that your graphics may not be supported if your graphics is a "UHD Graphics G1". Once you confirm which one you have I can confirm if it can be supported or not.

If it's the G1 model of UHD graphics the reason it cannot be supported is because no real Mac ever had it and the macOS drivers are not able to understand that chipset. It apparently is fundamentally different than the previous UHD models of the same name. 

If your model is a 6xx then we may be able to add support

**Comment by PremuimPython40** [comment] 2024-03-29 19:18
Ok i will see tomorrow

Met vriendelijke groet,

Jurre Stokkentre.


Op vr 29 mrt 2024 om 19:02 schreef balopez83 ***@***.***>

**Comment by PremuimPython40** [comment] 2024-03-30 08:05
*3-1005G1*

*Intel® UHD Graphics for 10th Gen Intel® Processors*


Op vr 29 mrt 2024 om 19:02 schreef balopez83 ***@***.***>

**Comment by balopez83** [comment] 2024-03-30 16:31
@PremuimPython40 Unfortunately it looks like that is an unsupported graphics chipset. While it has the same name as the prior generation it's my understanding that it cannot be spoofed as it uses a different design than prior generations. Since macOS never supported that chipset there isn't anything that can be done to get it to work.

Sorry I don't have better news.

**Comment by balopez83** [comment] 2024-04-01 03:12
@PremuimPython40 since it appears it will not be possible to get the i3 supported I am going to close this issue. If in the future I can find a way to get it running, I will add that support.

**Closed by balopez83** 2024-04-01 03:12 UTC
